spring:
  datasource:
    url: jdbc:mysql://localhost:3306/transactions
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

  liquibase:
    change-log: classpath:db/changelog/changelog.xml
